### ISSUE TITLE
about dmt io emulator

### ISSUE THREAD

**Issue by neosys131** [unlimitedsola/dmt-io-emulator#1]
hello

when i run this program, it closes in a second.

can you tell me how to use it?

**Comment by unlimitedsola** [comment]
I feel proud that my little toy got someone's eyes. :smiley: 

Here is the usage:

0. First thing first, you must have the `net` icon on for your DJMax Technica 3 machine, with that being said, you must have a connection to someone's private server.
1. Then, you're gonna need a virtual serial port to connect COM9 with COM6 bidirectionally, there are many software out there can do this, e.g. [vspd-driver](https://www.eltima.com/products/vspdxp/)
2. Open the program you've compiled or downloaded from the releases page. Open it up and you should be good to go.
3. If you want to change the card id of your login, edit the `card.json` file according to its format.

**Comment by neosys131** [comment]
Hello
can you make this to be work only as io? 
i mean only test and service :)
because i own technika 1 and 2

**Comment by unlimitedsola** [comment]
how would you like to trigger it? via keyboard hotkey?

**Comment by neosys131** [comment]
yes via keyboard kotkey :)
and i want to use my card reader as normally
only io as hot key !
